import { Sparkles } from "lucide-react";
import { AnalysisCard } from "./AnalysisCard";

interface AiSummaryCardProps {
  summary: string;
  className?: string;
}

export function AiSummaryCard({ summary, className = "lg:col-span-2" }: AiSummaryCardProps) {
  return (
    <AnalysisCard
      title="AI Summary"
      subtitle="Generated by ProductReady AI"
      icon={<Sparkles className="w-4 h-4" />}
      className={className}
    >
      <p className="text-[13px] leading-relaxed text-gray-600">{summary}</p>
    </AnalysisCard>
  );
}